# Generated by Django 4.0.5 on 2023-11-14 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0002_alter_lineatransversalmodel_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoDigitalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingresa el nombre del contenido', max_length=50, unique=True, verbose_name='Nombre contenido')),
                ('url', models.CharField(help_text='Ingresa la url del contenido', max_length=50, verbose_name='Url contenido')),
                ('visibilidad', models.BooleanField(default=False, help_text='Selecciones la visibilidad', verbose_name='Visibilidad')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', help_text='Seleccione el estado', max_length=50, verbose_name='Estado')),
                ('recomendacion', models.CharField(default='Sin recomendación', help_text='Asigne una Recomendación', max_length=500, null=True, verbose_name='Recomendacion')),
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creacion')),
                ('fecha_aprobacion', models.DateTimeField(null=True, verbose_name='Fecha de aprobación')),
                ('id_linea', models.ForeignKey(help_text='Id linea', on_delete=django.db.models.deletion.DO_NOTHING, to='shared.lineatransversalmodel', verbose_name='Id linea')),
                ('user', models.ForeignKey(help_text='Seleccione Usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Contenido digital',
                'verbose_name_plural': 'Contenidos digitales',
            },
        ),
    ]
