# Generated by Django 4.0.5 on 2023-11-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condigitales', '0002_alter_contenidodigitalmodel_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidodigitalmodel',
            name='visibilidad',
            field=models.BooleanField(help_text='Selecciones la visibilidad', verbose_name='Visibilidad'),
        ),
    ]
