# Generated by Django 4.0.5 on 2023-11-15 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_poblacionmodel'),
        ('condigitales', '0004_contenidodigitalmodel_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidodigitalmodel',
            name='id_poblacion',
            field=models.ForeignKey(help_text='Id población', on_delete=django.db.models.deletion.DO_NOTHING, to='shared.poblacionmodel', verbose_name='Id población'),
        ),
    ]
