# Generated by Django 4.0.5 on 2023-11-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condigitales', '0005_alter_contenidodigitalmodel_id_poblacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidodigitalmodel',
            name='fecha_creacion',
            field=models.DateTimeField(verbose_name='Fecha de Creacion'),
        ),
    ]
