# Generated by Django 4.0.5 on 2023-11-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condigitales', '0007_remove_contenidodigitalmodel_imagen_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidodigitalmodel',
            name='url',
            field=models.CharField(blank=True, help_text='Ingresa la url del contenido', max_length=50, null=True, verbose_name='Url contenido'),
        ),
    ]
