# Generated by Django 4.0.5 on 2023-11-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condigitales', '0008_alter_contenidodigitalmodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidodigitalmodel',
            name='archivo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='contenidos/', verbose_name='Archivo'),
        ),
    ]
