# Generated by Django 4.0.5 on 2023-12-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condigitales', '0009_alter_contenidodigitalmodel_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidodigitalmodel',
            name='url',
            field=models.CharField(blank=True, help_text='Ingresa la url del contenido', max_length=500, null=True, verbose_name='Url contenido'),
        ),
    ]
