# Generated by Django 4.0.5 on 2023-11-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineatransversalmodel',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe una linea transversal con este nombre.'}, help_text='Asigne un nombre a la linea transversal', max_length=30, unique=True, verbose_name='Nombre de linea transversal'),
        ),
    ]
