# Generated by Django 4.0.5 on 2023-11-23 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_poblacionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenciaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Asigne un nombre a la competencia', max_length=30, verbose_name='Nombre de la competencia')),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
            },
        ),
        migrations.CreateModel(
            name='TemaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Asigne un nombre al tema', max_length=30, verbose_name='Nombre del tema')),
                ('id_competencia', models.ManyToManyField(help_text='Id competencia', related_name='temas', to='shared.competenciamodel', verbose_name='Id competencia')),
                ('id_linea', models.ForeignKey(help_text='Id linea', on_delete=django.db.models.deletion.DO_NOTHING, to='shared.lineatransversalmodel', verbose_name='Id linea')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
    ]
