# Generated by Django 4.0.5 on 2023-11-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_competenciamodel_temamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competenciamodel',
            name='nombre',
            field=models.CharField(help_text='Asigne un nombre a la competencia', max_length=500, verbose_name='Nombre de la competencia'),
        ),
        migrations.AlterField(
            model_name='lineatransversalmodel',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe una linea transversal con este nombre.'}, help_text='Asigne un nombre a la linea transversal', max_length=100, unique=True, verbose_name='Nombre de linea transversal'),
        ),
        migrations.AlterField(
            model_name='temamodel',
            name='nombre',
            field=models.CharField(help_text='Asigne un nombre al tema', max_length=500, verbose_name='Nombre del tema'),
        ),
    ]
