# Generated by Django 4.0.5 on 2023-10-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformationmodel',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='userinformationmodel',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Apellidos'),
        ),
    ]
