# Generated by Django 4.0.5 on 2023-10-31 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinformationmodel_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformationmodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userinformationmodel',
            name='last_name',
        ),
    ]
