# Generated by Django 4.0.5 on 2023-11-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userinformationmodel_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformationmodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='userinformationmodel',
            name='identification',
            field=models.CharField(blank=True, default='Sin número de identificación', help_text='Ingresa número de identificación', max_length=20, verbose_name='Número de identificación'),
        ),
    ]
