# Generated by Django 4.0.5 on 2023-11-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_userinformationmodel_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformationmodel',
            name='identification',
            field=models.CharField(help_text='Ingresa número de identificación', max_length=30, unique=True, verbose_name='Número de identificación'),
        ),
    ]
