# Generated by Django 4.0.5 on 2023-11-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userinformationmodel_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformationmodel',
            name='user_type',
            field=models.CharField(choices=[('1', 'Administrativo'), ('2', 'Lider PPT'), ('3', 'Docente')], default='3', help_text='Seleccione un tipo de usuario', max_length=255, verbose_name='Tipo de usuario'),
        ),
    ]
