# Generated by Django 4.0.5 on 2023-11-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userinformationmodel_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformationmodel',
            name='identification',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con este número de identificación.'}, help_text='Ingresa número de identificación', max_length=30, unique=True, verbose_name='Número de identificación'),
        ),
    ]
