# Generated by Django 4.0.5 on 2023-12-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_userinformationmodel_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformationmodel',
            name='user_type',
            field=models.CharField(choices=[('0', 'Administrativo'), ('1', 'Lider Emprendimiento'), ('2', 'Lider Sexualidad'), ('3', 'Lider Relaciones Sociales'), ('4', 'Lider Medio Ambiente'), ('5', 'Lider TICS'), ('6', 'Docente')], help_text='Seleccione un tipo de usuario', max_length=255, verbose_name='Tipo de usuario'),
        ),
    ]
