# Generated by Django 4.0.5 on 2023-12-14 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyectos_emprendimiento', models.IntegerField(null=True, verbose_name='Proyectos de emprendimiento')),
                ('proyectos_sexualidad', models.IntegerField(null=True, verbose_name='Proyectos de sexualidad')),
                ('proyectos_relaciones_sociales', models.IntegerField(null=True, verbose_name='Proyectos de relaciones sociales')),
                ('proyectos_medio_ambiente', models.IntegerField(null=True, verbose_name='Proyectos de medio ambiente')),
                ('proyectos_tics', models.IntegerField(null=True, verbose_name='Proyectos de tics')),
                ('contenidos_emprendimiento', models.IntegerField(null=True, verbose_name='Contenidos de emprendimiento')),
                ('contenidos_sexualidad', models.IntegerField(null=True, verbose_name='Contenidos de sexualidad')),
                ('contenidos_relaciones_sociales', models.IntegerField(null=True, verbose_name='Contenidos de relaciones sociales')),
                ('contenidos_medio_ambiente', models.IntegerField(null=True, verbose_name='Contenidos de medio ambiente')),
                ('contenidos_tics', models.IntegerField(null=True, verbose_name='Contenidos de tics')),
                ('herramientas_emprendimiento', models.IntegerField(null=True, verbose_name='Herramientas de emprendimiento')),
                ('herramientas_sexualidad', models.IntegerField(null=True, verbose_name='Herramientas de sexualidad')),
                ('herramientas_relaciones_sociales', models.IntegerField(null=True, verbose_name='Herramientas de relaciones sociales')),
                ('herramientas_medio_ambiente', models.IntegerField(null=True, verbose_name='Herramientas de medio ambiente')),
                ('herramientas_tics', models.IntegerField(null=True, verbose_name='Herramientas de tics')),
                ('user', models.OneToOneField(help_text='Seleccione Usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estadistica',
                'verbose_name_plural': 'Estadisticas',
            },
        ),
    ]
