# Generated by Django 4.0.5 on 2023-12-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatsmodel',
            name='contenidos_emprendimiento',
            field=models.IntegerField(default=0, null=True, verbose_name='Contenidos de emprendimiento'),
        ),
        migrations.AlterField(
            model_name='userstatsmodel',
            name='contenidos_medio_ambiente',
            field=models.IntegerField(default=0, null=True, verbose_name='Contenidos de medio ambiente'),
        ),
        migrations.AlterField(
            model_name='userstatsmodel',
            name='contenidos_relaciones_sociales',
            field=models.IntegerField(default=0, null=True, verbose_name='Contenidos de relaciones sociales'),
        ),
        migrations.AlterField(
            model_name='userstatsmodel',
            name='contenidos_sexualidad',
            field=models.IntegerField(default=0, null=True, verbose_name='Contenidos de sexualidad'),
        ),
        migrations.AlterField(
            model_name='userstatsmodel',
            name='contenidos_tics',
            field=models.IntegerField(default=0, null=True, verbose_name='Contenidos de tics'),
        ),
        migrations.AlterField(
            model_name='userstatsmodel',
            name='herramientas_emprendimiento',
            field=models.IntegerField(default=0, null=True, verbose_name='Herramientas de emprendimiento'),
        ),
        migrations.AlterField(
            model_name='userstatsmodel',
            name='herramientas_medio_ambiente',
            field=models.IntegerField(default=0, null=True, verbose_name='Herramientas de medio ambiente'),
        ),
        migrations.AlterField(
            model_name='userstatsmodel',
            name='herramientas_relaciones_sociales',
            field=models.IntegerField(default=0, null=True, verbose_name='Herramientas de relaciones sociales'),
        ),
        migrations.AlterField(
            model_name='userstatsmodel',
            name='herramientas_sexualidad',
            field=models.IntegerField(default=0, null=True, verbose_name='Herramientas de sexualidad'),
        ),
        migrations.AlterField(
            model_name='userstatsmodel',
            name='herramientas_tics',
            field=models.IntegerField(default=0, null=True, verbose_name='Herramientas de tics'),
        ),
        migrations.AlterField(
            model_name='userstatsmodel',
            name='proyectos_emprendimiento',
            field=models.IntegerField(default=0, null=True, verbose_name='Proyectos de emprendimiento'),
        ),
        migrations.AlterField(
            model_name='userstatsmodel',
            name='proyectos_medio_ambiente',
            field=models.IntegerField(default=0, null=True, verbose_name='Proyectos de medio ambiente'),
        ),
        migrations.AlterField(
            model_name='userstatsmodel',
            name='proyectos_relaciones_sociales',
            field=models.IntegerField(default=0, null=True, verbose_name='Proyectos de relaciones sociales'),
        ),
        migrations.AlterField(
            model_name='userstatsmodel',
            name='proyectos_sexualidad',
            field=models.IntegerField(default=0, null=True, verbose_name='Proyectos de sexualidad'),
        ),
        migrations.AlterField(
            model_name='userstatsmodel',
            name='proyectos_tics',
            field=models.IntegerField(default=0, null=True, verbose_name='Proyectos de tics'),
        ),
    ]
