# Generated by Django 4.0.5 on 2023-11-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0003_rename_objetivos_herramientamodel_objetivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramientamodel',
            name='fecha_creacion',
            field=models.DateTimeField(null=True, verbose_name='Fecha de Creacion'),
        ),
    ]
