# Generated by Django 4.0.5 on 2023-11-24 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0008_momentomodel_id_herramienta_procesomodel_id_momento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momentomodel',
            name='id_herramienta',
            field=models.ForeignKey(help_text='Id herramienta', on_delete=django.db.models.deletion.DO_NOTHING, to='herramientas.herramientamodel', verbose_name='Id herramienta'),
        ),
        migrations.AlterField(
            model_name='procesomodel',
            name='id_momento',
            field=models.ForeignKey(help_text='Id momento', on_delete=django.db.models.deletion.DO_NOTHING, to='herramientas.momentomodel', verbose_name='Id momento'),
        ),
    ]
