# Generated by Django 4.0.5 on 2023-11-24 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_alter_competenciamodel_nombre_and_more'),
        ('herramientas', '0009_alter_momentomodel_id_herramienta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesomodel',
            name='id_recurso',
            field=models.ManyToManyField(help_text='Id recurso', related_name='procesos', to='herramientas.recursomodel', verbose_name='Id recurso'),
        ),
        migrations.AlterField(
            model_name='herramientamodel',
            name='id_tema',
            field=models.ForeignKey(help_text='Id tema', on_delete=django.db.models.deletion.CASCADE, to='shared.temamodel', verbose_name='Id tema'),
        ),
        migrations.AlterField(
            model_name='momentomodel',
            name='id_herramienta',
            field=models.ForeignKey(help_text='Id herramienta', on_delete=django.db.models.deletion.CASCADE, to='herramientas.herramientamodel', verbose_name='Id herramienta'),
        ),
        migrations.AlterField(
            model_name='procesomodel',
            name='id_momento',
            field=models.ForeignKey(help_text='Id momento', on_delete=django.db.models.deletion.CASCADE, to='herramientas.momentomodel', verbose_name='Id momento'),
        ),
    ]
