# Generated by Django 4.0.5 on 2023-12-11 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoaula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadmodel',
            name='id_proyectoaula',
            field=models.ForeignKey(help_text='Id proyecto aula', on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='proyectoaula.proyectoaulamodel', verbose_name='Id proyecto aula'),
        ),
    ]
